name: Build, Test, and (maybe) Deploy React Application

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install aqtinstall - requirement for functional tests
        run: pip install aqtinstall
      - name: yarn install, build and test
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn run build --if-present
          yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: deploy to gh-pages
        if: github.ref == 'refs/heads/main' && github.actor == github.repository_owner
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
